# Managed by Puppet
global_defs {
  snmp_socket unix:/var/agentx/master
  vrrp_notify_fifo /var/run/keepalived.floaty.fifo
  vrrp_notify_fifo_script /usr/sbin/floaty-global.wrapper.sh
}

include /etc/keepalived/conf.d/*
