# Enable IPv4 forwarding
net.ipv4.ip_forward = 1

# Enable non-local bind
net.ipv4.ip_nonlocal_bind = 1
net.ipv6.ip_nonlocal_bind = 1

# Disable TCP MTU probing and enable TCP SACK
net.ipv4.tcp_mtu_probing = 0
net.ipv4.tcp_sack = 1

# Disable IPv6 duplicate address detection
net.ipv6.conf.all.accept_dad = 0
net.ipv6.conf.default.accept_dad = 0
